import Head from 'next/head';

interface CustomHeadProps {
  title: string;
}

export default function CustomHead ({ title }: CustomHeadProps) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};


